### ISSUE TITLE
Cannot ran pre-compiled binary in ncurses branch

### ISSUE THREAD

**Issue by Vitaspiros** [ikozyris/yocto#18]
## Expected behavior
When typing _ , as stated in the instructions, the program must replace _ with a space character.
## Current behavior
The program does not replace _ (underscores) with spaces.
## Specs
```
OS: Ubuntu 20.04
Program ran from: pre-compiled binary
```

It seems like the pre-compiled binary in the `Binaries` directory is outdated because when the program is built from source and then ran, its behavior is as expected. Please fix.

**Comment by Vitaspiros** [comment]
I just discovered that there is a `Text-editor_0.6` file in the `Binaries` directory. Probably, it's the most updated version. But I can't test because when I try to ran it throws me this message:
 ```./Text-editor_0.6: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./Text-editor_0.6)```

Changing the title.

**Comment by ikozyris** [comment]
That binary is obsolete and is not ncurses. The ncurses source file is the main.c

**Comment by ikozyris** [comment]
For the OP: It says that because it couldn't read spaces. Anyway, it is an older version and will be removed to avoid confusion.
